AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'

Layout/EndOfLine:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

  