version: "3.9"
services:
  db:
    image: postgis/postgis:11-3.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    environment:
      - RAILS_ENV=docker
    ports:
      - "3000:3000"
    depends_on:
      - db
